# Generated by Django 4.1.5 on 2023-01-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('product_description', models.TextField(verbose_name=500)),
                ('item_price', models.FloatField()),
                ('product_image', models.CharField(max_length=500)),
            ],
        ),
    ]
